services:
  # 1. Cơ sở dữ liệu: TimescaleDB (PostgreSQL)
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: navis_db
    environment:
      POSTGRES_USER: navis_admin
      POSTGRES_PASSWORD: navis_password_123
      POSTGRES_DB: navis_cloud
    ports:
      - "5432:5432"
    volumes:
      - navis_db_data:/var/lib/postgresql/data

  # 2. Hệ thống quản lý cho Kafka 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: navis_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 3. Message Broker: Kafka 
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: navis_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  navis_db_data: